[package]
name = "talos"
version = "0.1.0"
description = "Solves \"The Talos Principle\" game puzzles"
authors = ["tarpaha <ppopchikovsky@gmail.com>"]
repository = "https://github.com/tarpaha/talos.git"
edition = "2018"

[dependencies]
clap = "2.33.3"
rand = "0.9.1"
